### ISSUE TITLE
Question: is there a plan to allow automatical detection of variables in the global environment used by the function like with {future}

### ISSUE THREAD

**Issue by xiaodaigh** [shikokuchuo/mirai#2]

**Comment by shikokuchuo** [comment]
First of all thanks for the question.

This could potentially make mirai’s API even more minimalistic.

Currently, if `x` is defined in the global environment (or on the search path from the calling environment), all you would have to do is add `x = x` to the `eval_mirai()` call. There is a certain cleanness to making sure all variables are explicitly passed, and makes it easier to reason with code.

If evaluation fails in the background process, a nul byte is returned to signal an error. This is robust and means there is an error in the user code. If we attempt to pre-parse the expression for global variables, this adds a potential point of failure and then makes it impossible to distinguish between a bug in our code or an error in the user’s code.

I have not looked at the source code for ‘future’ so I do not know how they handle this. If it is a particularly simple and elegant solution, I may be amenable. Please feel free to point me to the code in question. I am also open to a PR (but please check with me first to ensure the approach is acceptable).

This is not high-priority otherwise.

**Comment by xiaodaigh** [comment]
future has a function called `future::getGlobalsAndPackages()` which accepts an expression and can detect automatically all the variables and package being used.

in the past, parallel, also has ability to run code in another process but it was not easy to use since it didnt' detect all globals. that's why many people use future instead.

**Comment by shikokuchuo** [comment]
That has behind it `globals::findGlobals` by the same author. As I suspected, it is not at all simple. The entire *package* 'globals' is dedicated to this, and looking at the list of outstanding issues at the repo, it is by no means foolproof.

mirai will not be going down this route. Simplicity of user interface is just one consideration, simplicity and robustness of code is another. Introducing something that is not guaranteed to work 100% of the time creates a potential point of failure and is not desirable as I mentioned previously.

Honestly I don't see that much benefit, if you think of `eval_mirai()` like any other function, the variables need to be passed in e.g. x = x, y = y.

Thanks though for the suggestion. If you have others, please feel free to share - mirai is a completely new approach, so it can do things differently.

**Comment by wlandau** [comment]
FWIW I agree with this direction, `mirai` is low-level and fast enough that I want to be 100% sure I avoid accidentally shipping large globals.

I actually quite like `callr`'s interface with explicit `fun` and `args` arguments. Either way seems fine for `mirai`, I can just use `do.call(what = eval_mirai, args = list(.expr = x + y, x = x, y = y))`. Just wondering what kinds of interfaces you are/were considering.

**Comment by shikokuchuo** [comment]
Cool! That’s fantastic with the `do.call()`. 

Noted on the 'fun' and 'args' – I would consider that the ‘classic’ approach. The mirai approach is slightly different but probably more natural for arbitrary expressions in { } - will be in the next CRAN release, already in the dev version on rOpenSci R-universe.

There is no intention for any change. mirai was really designed for a specific use case I had, but if others are finding other uses and there are obvious changes to make it fit easier with workflows, I am open to suggestions.

The only upcoming change is adding a `wait` argument to `call_mirai()`, which will default to TRUE for it to be non-breaking. This is useful in situation where you don’t know if the async operation has completed and you don’t want to end up with a blocking wait. It’s already in the dev version.

Incidentally the decision for this non-waiting call to return NULL if the mirai is yet to resolve is partly due the other question I received about use in Shiny – the NULL would provide a ‘non-truthy’ value it can reason with within its reactive framework.

**Comment by wlandau** [comment]
Yeah, the non-blocking `call_mirai()` is vital for what I have in mind. Really glad you are working on that.
