### ISSUE TITLE
unresolved() and data

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#37]
This topic has been low on my priority list until now, and it is by no means urgent, but I would like to discuss.

`crew` keeps the `mirai` objects of all the current tasks, and it needs to know which tasks are complete in order to do auto-scaling. To make decisions about when to launch new workers, `crew` compares the number of active workers to the number of incomplete tasks. To count the number of incomplete tasks, I cannot use counters `tasks_assigned` or `tasks_complete` because they only count tasks that have been assigned to a worker (ignoring the unassigned backlog) and because they reset every time a new worker connects to the socket. So instead, `crew` calls `unresolved()` on each `mirai()` object in the task list before making a decision about how many workers to launch. These launching decisions happen frequently (every `push()` and `pop()`, as well as every fraction of a second in `wait()`), so I would strongly prefer `unresolved()` to be fast.

As you explained in an earlier thread, `unresolved()` downloads the data in order to check if the task is complete. For most cases this may not be much of an issue, but for large enough data, this could slow down `crew` because of what needs to happen for auto-scaling. Also, it risks running into a situation where we have large objects from multiple tasks simultaneously in memory, and memory may not be adequate to store everything in a single session.

Would it be possible to allow `unresolved()` to avoid downloading the data so it can be fast and lightweight for medium to large data? Here is what I see with `mirai` 0.8.1:

```r
library(mirai)
library(lobstr)
daemons(n = 1L, url = "ws://127.0.0.1:5001", dispatcher = TRUE)
#> [1] 1
server <- callr::r_bg(function() mirai::server("ws://127.0.0.1:5001"))
daemons()
#> $connections
#> [1] 1
#> 
#> $daemons
#> status_online status_busy tasks_assigned tasks_complete instance #
#> ws://127.0.0.1:5001             1           0              0              0          1
m <- mirai(rnorm(1e8))
Sys.sleep(10)
obj_size(m)
#> 6.01 kB
system.time(available <- !unresolved(m))
#> user  system elapsed 
#> 1.572   0.500   2.078
available
#> [1] TRUE
obj_size(m)
#> 800.01 MB
system.time(unresolved(m))
#> user  system elapsed 
#> 0       0       0
system.time(size <- obj_size(m$data))
#> user  system elapsed 
#> 0       0       0 
size
#> 800.00 MB
daemons(n = 0L)
#> [1] 0
server$kill()
```

**Comment by shikokuchuo** [comment]
To be precise, how `unresolved()` is implemented, it simply queries the active binding, which is `$data`.

The active binding function calls get data which either returns immediately if there is nothing there or it actually gets the data, and this is where you can find it takes time with large objects as in your example above.

 Needless to say all this is at the C level, which I'm sure you've discovered.

`unresolved()` is implemented this way to present a consistent interface, which would lead to subtle bugs otherwise. So that if someone is relying on `unresolved()`, you can be sure that the data is simply there at `$data` as you'd expect. I'm not sure I can think of a good example off the top of my head where it would break, but suffice to say there is a good reason it is implemented like this.

However, back to your problem. Yes I do believe there is a straightforward way of simply querying the status of the `mirai`, which I can expose in the next version of `nanonext` to solve this particular problem. I would probably need to think of some obscure name for the function so that it won't cause confusion!

**Comment by wlandau** [comment]
Thank you so much for considering this additional functionality via `nanonext`. It sounds like `unresolved()` has a robust implementation, and I agree it would make sense to leave working as is.

**Comment by shikokuchuo** [comment]
I've given you this as `.unresolved()` in the latest build of nanonext. You will have access to this when the next version is released.

**Comment by wlandau** [comment]
`nanonext::.unresolved()` is perfect, thank you so much!
