### ISSUE TITLE
Optional server connection timeout to avoid waiting forever for a client

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#44]
We discussed at https://github.com/wlandau/crew/issues/51#issuecomment-1485349386, but it was a digression there.

**Comment by shikokuchuo** [comment]
We should think on this more. Does adding another option encourage the right behaviour or would it be  better to always set 'idletime' where this issue is important?

Alternatively perhaps the default for 'asyncdial' should be FALSE.

**Comment by wlandau** [comment]
Yeah, maybe `crew` should set `asyncdial` to `FALSE` for its own servers. I wonder though, how much more susceptible would that make `crew` to temporary network interruptions which would otherwise resolve themselves a millisecond later?

**Comment by shikokuchuo** [comment]
Yes, I would be supportive of such a change. I don't think it would be susceptible to the kind of network interruptions you imagine - TCP is fairly robust - otherwise the manifestation would be constant connects / disconnects. Rather, it's just required that the listener is in place at the port the server is dialling.

For crew, if the controller is always supposed to be in place before a launcher then I think that's a safe assumption, even if the commands are executed sequentially as there will presumably be some latency to the launcher - sending to remote server, starting up an R session etc.

I would make the change at 'mirai' but currently (as there is no launcher orchestration for remote processes), it makes more sense for manually launched servers to dial async, so that the order doesn't matter.

**Comment by wlandau** [comment]
Thanks for confirming. I am totally fine with manually setting `asyncdial = FALSE` manually in `crew`. Implemented in https://github.com/wlandau/crew/commit/fd8f8c3382bc3ac44b29951ef43db0cc7a25fb4a.
