### ISSUE TITLE
Incongrous instance statistics

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/mirai#68]
As the task statistics `assigned` and `complete` are now cumulative, it seems odd especially on `crew` workflows to have potentially thousands of results and instance as always '1'.

It is also impossible to tell if many servers have connected or just the one, and would have made something like https://github.com/shikokuchuo/mirai/issues/65#issuecomment-1670241271 obvious.

The solution would be to make this a cumulative counter as well - not reset to zero on `saisei()`. For `crew` logic compatibility, it can instead be made negative when the URL is regenerated by `saisei()`. Then when a new dameon connects, it simply takes the absolute value of the counter and increments it.

@wlandau I believe this does not require any change to `crew` as I think you use inequality checkers rather than any explicit `instance == 0L` anywhere, and it tests fine, but flagging just in case.

**Comment by wlandau** [comment]
Unfortunately, https://github.com/shikokuchuo/mirai/commit/9dadda96bef962f89c02bab418912341caace87c breaks throughput tests like https://github.com/wlandau/crew/blob/main/tests/throughput/test-backlog-tasks_max.R because of the launcher uses [`discovered <- as.logical(daemons[, "instance"])`](https://github.com/wlandau/crew/blob/8d387acef8414320c20985e481fc99e95b45b84c/R/crew_launcher.R#L417) to check if a worker ever connected. My patch in https://github.com/wlandau/crew/commit/93ed08b2ca14ceaf90a8378115ada97611ca7ee6 easily fixes this by changing to `discovered <- as.logical(daemons[, "instance"] > 0L)`. I aim to update `crew` on CRAN on August 23, but unfortunately I cannot submit it any earlier because of submission quotas.

**Comment by shikokuchuo** [comment]
That's perfect! No rush as the CRAN release for mirai is even later. Thanks for the patch.
